package app.cursos.techcenter.view;

import app.cursos.techcenter.controller.TechCenterController;
import app.cursos.techcenter.model.Cursos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ActCursosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActCursosView
     */
    public ActCursosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtMatriculados = new javax.swing.JTextField();
        txtNomCurso = new javax.swing.JTextField();
        txtProfesor = new javax.swing.JTextField();
        txtVacantes = new javax.swing.JTextField();
        btnConsultarCurso = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtIdCurso = new javax.swing.JTextField();
        btnActCurso = new javax.swing.JButton();

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ACTUALIZAR CURSOS");

        txtMatriculados.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriculados.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtMatriculados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matriculados actuales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNomCurso.setBackground(new java.awt.Color(255, 255, 255));
        txtNomCurso.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNomCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtProfesor.setBackground(new java.awt.Color(255, 255, 255));
        txtProfesor.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtVacantes.setBackground(new java.awt.Color(255, 255, 255));
        txtVacantes.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtVacantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vacantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnConsultarCurso.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarCurso.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarCurso.setText("CONSULTAR CURSO");
        btnConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCursoActionPerformed(evt);
            }
        });

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtIdCurso.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCurso.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtIdCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID de curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnActCurso.setBackground(new java.awt.Color(153, 255, 153));
        btnActCurso.setForeground(new java.awt.Color(0, 0, 0));
        btnActCurso.setText("ACTUALIZAR CURSO");
        btnActCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomCurso)
                                    .addComponent(txtMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtProfesor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(txtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnActCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel11))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCursoActionPerformed
        try {
            TechCenterController control = new TechCenterController();

            //Seteando datos curso
            txtNomCurso.setText(control.buscarCurso(Integer.parseInt(txtIdCurso.getText())).getNombre());
            txtVacantes.setText(Integer.toString(control.buscarCurso(Integer.parseInt(txtIdCurso.getText())).getNum_vacantes()));
            txtProfesor.setText(control.buscarCurso(Integer.parseInt(txtIdCurso.getText())).getProfesor());
            txtPrecio.setText(Double.toString(control.buscarCurso(Integer.parseInt(txtIdCurso.getText())).getPrecio()));
            txtMatriculados.setText(Integer.toString(control.buscarCurso(Integer.parseInt(txtIdCurso.getText())).getNum_matriculados()));
        } catch (SQLException ex) {
            Logger.getLogger(RegMatriculasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarCursoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActCursoActionPerformed
        try {
            // Obtener los datos ingresados por el usuario para actualizar el empleado
            int idCurso = Integer.parseInt(txtIdCurso.getText());
            String nomCurso = txtNomCurso.getText();
            int numVacantes = Integer.parseInt(txtVacantes.getText());
            int numMatriculados = Integer.parseInt(txtMatriculados.getText());
            String nomProfesor= txtProfesor.getText();
            double precio= Double.parseDouble(txtPrecio.getText());

            // Crear un objeto Empleado con los datos recopilados
            Cursos curso = new Cursos(idCurso, nomCurso, numVacantes, numMatriculados, nomProfesor, precio);

            // Llamar al método ActEmpleado para actualizar los datos del empleado
            TechCenterController control = new TechCenterController(); 
            Cursos cursoActualizado = control.ActCurso(curso); 

            // Verificar si la actualización fue exitosa y mostrar un mensaje
            if (cursoActualizado != null) {
                JOptionPane.showMessageDialog(this, "Datos del curso actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el curso.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en el formato de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActCurso;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarCurso;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JTextField txtIdCurso;
    private javax.swing.JTextField txtMatriculados;
    private javax.swing.JTextField txtNomCurso;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProfesor;
    private javax.swing.JTextField txtVacantes;
    // End of variables declaration//GEN-END:variables
}
