package app.cursos.techcenter.view;

import app.cursos.techcenter.controller.TechCenterController;
import app.cursos.techcenter.model.Empleado;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ActEmpleadoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActEmpleadoView
     */
    public ActEmpleadoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDireccionEmpleado = new javax.swing.JTextField();
        txtNomEmpleado = new javax.swing.JTextField();
        txtEmailEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        btnConsultarEmpleado = new javax.swing.JButton();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        txtIdEmpleado = new javax.swing.JTextField();
        btnActEmpleado = new javax.swing.JButton();

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ACTUALIZAR EMPLEADOS");

        txtDireccionEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtDireccionEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNomEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtNomEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNomEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtEmailEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtEmailEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtApellidoEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtApellidoEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnConsultarEmpleado.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarEmpleado.setText("CONSULTAR EMPLEADO");
        btnConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpleadoActionPerformed(evt);
            }
        });

        txtUsuarioEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtUsuarioEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtContra.setBackground(new java.awt.Color(255, 255, 255));
        txtContra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtIdEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtIdEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID de empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        btnActEmpleado.setBackground(new java.awt.Color(153, 255, 153));
        btnActEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnActEmpleado.setText("ACTUALIZAR EMPLEADO");
        btnActEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNomEmpleado)
                        .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConsultarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEmailEmpleado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtContra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel11))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnActEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpleadoActionPerformed
        try {
            TechCenterController control = new TechCenterController();

            //Seteando datos empleado
            txtEmailEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getEmail());
            txtDireccionEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getDireccion());
            txtNomEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getNombre());
            txtApellidoEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getApellido());
            txtUsuarioEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getUsuario());
            txtContra.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getContraseña());

        } catch (SQLException ex) {
            Logger.getLogger(RegMatriculasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarEmpleadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActEmpleadoActionPerformed
        try {
            // Obtener los datos ingresados por el usuario para actualizar el empleado
            int idEmpleado = Integer.parseInt(txtIdEmpleado.getText());
            String apeEmpleado= txtApellidoEmpleado.getText();
            String nomEmpleado = txtNomEmpleado.getText();
            String direcEmpleado = txtDireccionEmpleado.getText();
            String emailEmpleado = txtEmailEmpleado.getText();
            String usuarioEmp= txtUsuarioEmpleado.getText();
            String contraEmp= String.valueOf(txtContra.getPassword());

            // Crear un objeto Empleado con los datos recopilados
            Empleado empleado = new Empleado(idEmpleado, apeEmpleado, nomEmpleado, direcEmpleado, emailEmpleado, usuarioEmp, contraEmp);

            // Llamar al método ActEmpleado para actualizar los datos del empleado
            TechCenterController control = new TechCenterController(); // Asegúrate de cambiar "TechCenterController" a la clase adecuada de tu capa de control
            Empleado empleadoActualizado = control.ActEmpleado(empleado); // Asegúrate de que el método ActEmpleado exista en tu controlador y realice la actualización

            // Verificar si la actualización fue exitosa y mostrar un mensaje
            if (empleadoActualizado != null) {
                JOptionPane.showMessageDialog(this, "Datos del empleado actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en el formato de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActEmpleadoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActEmpleado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarEmpleado;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JTextField txtEmailEmpleado;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNomEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
