package app.cursos.techcenter.view;

import app.cursos.techcenter.model.Empleado;
import app.cursos.techcenter.util.Session;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

public class MainTechCenterView extends javax.swing.JFrame {

    /**
     * Creates new form MainTechCenterView
     */
    public MainTechCenterView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        establecerTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuProc = new javax.swing.JMenu();
        menuProcesosResgistrarAlumno = new javax.swing.JMenuItem();
        menuProcesosRegistrarEmpleado = new javax.swing.JMenuItem();
        menuProcesosMatricularAlumno = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasConsultarAlumno = new javax.swing.JMenuItem();
        menuConsultasConsultarCurso = new javax.swing.JMenuItem();
        menuConsultasConsultarEmpleado = new javax.swing.JMenuItem();
        menuTablas = new javax.swing.JMenu();
        menuActDatosAlumno = new javax.swing.JMenuItem();
        menuActDatosCursos = new javax.swing.JMenuItem();
        menuActDatosEmpleado = new javax.swing.JMenuItem();
        menuUtil = new javax.swing.JMenu();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Educa System");

        menuProc.setText("Procesos");

        menuProcesosResgistrarAlumno.setText("Registrar alumno");
        menuProcesosResgistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosResgistrarAlumnoActionPerformed(evt);
            }
        });
        menuProc.add(menuProcesosResgistrarAlumno);

        menuProcesosRegistrarEmpleado.setText("Registrar empleado");
        menuProcesosRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosRegistrarEmpleadoActionPerformed(evt);
            }
        });
        menuProc.add(menuProcesosRegistrarEmpleado);

        menuProcesosMatricularAlumno.setText("Matricular alumno");
        menuProcesosMatricularAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosMatricularAlumnoActionPerformed(evt);
            }
        });
        menuProc.add(menuProcesosMatricularAlumno);

        menuBar.add(menuProc);

        menuConsultas.setText("Consultas");

        menuConsultasConsultarAlumno.setText("Consultar alumno");
        menuConsultasConsultarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasConsultarAlumnoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasConsultarAlumno);

        menuConsultasConsultarCurso.setText("Consultar curso");
        menuConsultasConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasConsultarCursoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasConsultarCurso);

        menuConsultasConsultarEmpleado.setText("Consultar empleado");
        menuConsultasConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasConsultarEmpleadoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasConsultarEmpleado);

        menuBar.add(menuConsultas);

        menuTablas.setText("Actualizar Datos");

        menuActDatosAlumno.setText("Actualizar alumnos");
        menuActDatosAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActDatosAlumnoActionPerformed(evt);
            }
        });
        menuTablas.add(menuActDatosAlumno);

        menuActDatosCursos.setText("Actualizar cursos");
        menuActDatosCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActDatosCursosActionPerformed(evt);
            }
        });
        menuTablas.add(menuActDatosCursos);

        menuActDatosEmpleado.setText("Actualizar empleados");
        menuActDatosEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActDatosEmpleadoActionPerformed(evt);
            }
        });
        menuTablas.add(menuActDatosEmpleado);

        menuBar.add(menuTablas);

        menuUtil.setText("Util");
        menuBar.add(menuUtil);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuProcesosResgistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosResgistrarAlumnoActionPerformed
        mostrarForm(RegAlumnoView.class);
    }//GEN-LAST:event_menuProcesosResgistrarAlumnoActionPerformed

    private void menuProcesosRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosRegistrarEmpleadoActionPerformed
        mostrarForm(RegEmpleadosView.class);
    }//GEN-LAST:event_menuProcesosRegistrarEmpleadoActionPerformed

    private void menuProcesosMatricularAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosMatricularAlumnoActionPerformed
        mostrarForm(RegMatriculasView.class);
    }//GEN-LAST:event_menuProcesosMatricularAlumnoActionPerformed

    private void menuConsultasConsultarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasConsultarAlumnoActionPerformed
        mostrarForm(ConAlumnosView.class);
    }//GEN-LAST:event_menuConsultasConsultarAlumnoActionPerformed

    private void menuConsultasConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasConsultarCursoActionPerformed
        mostrarForm(ConCursosView.class);
    }//GEN-LAST:event_menuConsultasConsultarCursoActionPerformed

    private void menuConsultasConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasConsultarEmpleadoActionPerformed
        mostrarForm(ConEmpleadoView.class);
    }//GEN-LAST:event_menuConsultasConsultarEmpleadoActionPerformed

    private void menuActDatosAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActDatosAlumnoActionPerformed
        mostrarForm(ActAlumnoView.class);
    }//GEN-LAST:event_menuActDatosAlumnoActionPerformed

    private void menuActDatosCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActDatosCursosActionPerformed
        mostrarForm(ActCursosView.class);
    }//GEN-LAST:event_menuActDatosCursosActionPerformed

    private void menuActDatosEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActDatosEmpleadoActionPerformed
        mostrarForm(ActEmpleadoView.class);
    }//GEN-LAST:event_menuActDatosEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTechCenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTechCenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTechCenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTechCenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTechCenterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem menuActDatosAlumno;
    private javax.swing.JMenuItem menuActDatosCursos;
    private javax.swing.JMenuItem menuActDatosEmpleado;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasConsultarAlumno;
    private javax.swing.JMenuItem menuConsultasConsultarCurso;
    private javax.swing.JMenuItem menuConsultasConsultarEmpleado;
    private javax.swing.JMenu menuProc;
    private javax.swing.JMenuItem menuProcesosMatricularAlumno;
    private javax.swing.JMenuItem menuProcesosRegistrarEmpleado;
    private javax.swing.JMenuItem menuProcesosResgistrarAlumno;
    private javax.swing.JMenu menuTablas;
    private javax.swing.JMenu menuUtil;
    // End of variables declaration//GEN-END:variables

    private void mostrarForm(Class<?> aClass) {
        try {
            // Variable de control
            JInternalFrame view = null;
            // Buscar instancia
            for (JInternalFrame form : desktopPane.getAllFrames()) {
                if (aClass.isInstance(form)) {
                    view = form;
                    break;
                }
            }
            // Crear instancia
            if (view == null) {
                view = (JInternalFrame) aClass.getConstructor().newInstance();
                desktopPane.add(view);
                view.setVisible(true);

                // Centrar el JInternalFrame en el JDesktopPane
                Dimension desktopSize = desktopPane.getSize();
                Dimension frameSize = view.getSize();
                int x = (desktopSize.width - frameSize.width) / 2;
                int y = (desktopSize.height - frameSize.height) / 2;
                view.setLocation(x, y);

                view.setMaximum(false);
            }
            view.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void establecerTitulo() {
        Empleado usuario= (Empleado) Session.get("usuario");
        String titulo= "EDUCA System [Usuario: "+ usuario.getNombre()+"]";
        this.setTitle(titulo);
    }
}
