package app.cursos.techcenter.view;

import app.cursos.techcenter.controller.TechCenterController;
import app.cursos.techcenter.model.Matricula;
import app.cursos.techcenter.model.Pago;
import app.cursos.techcenter.util.Mensaje;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RegMatriculasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MatriculasView
     */
    public RegMatriculasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnMatricularAlumno = new javax.swing.JButton();
        BtnBuscarDatos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbxNombreCurso = new javax.swing.JComboBox<>();
        txtNumVacantes = new javax.swing.JTextField();
        txtPrecioCurso = new javax.swing.JTextField();
        txtNomProfesor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtIdAlu = new javax.swing.JTextField();
        txtEmailAlu = new javax.swing.JTextField();
        txtNomAlumno = new javax.swing.JTextField();
        txtTelefonoAlu = new javax.swing.JTextField();
        txtDireccionAlumno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        txtEmailEmpleado = new javax.swing.JTextField();
        txtNomEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        txtDireccionEmpleado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        txtFechaPago = new javax.swing.JTextField();
        cbxNumCuotas = new javax.swing.JComboBox<>();
        cbxTipoMatri = new javax.swing.JComboBox<>();
        txtNota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnProcesarDatos = new javax.swing.JButton();

        setTitle("Matricular alumnos");

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("MATRICULAS: ");

        btnMatricularAlumno.setBackground(new java.awt.Color(153, 255, 153));
        btnMatricularAlumno.setForeground(new java.awt.Color(0, 0, 0));
        btnMatricularAlumno.setText("MATRICULAR ALUMNO");
        btnMatricularAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAlumnoActionPerformed(evt);
            }
        });

        BtnBuscarDatos.setBackground(new java.awt.Color(153, 255, 204));
        BtnBuscarDatos.setForeground(new java.awt.Color(0, 0, 0));
        BtnBuscarDatos.setText("BUSCAR DATOS");
        BtnBuscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarDatosActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Curso Datos");

        cbxNombreCurso.setBackground(new java.awt.Color(255, 255, 255));
        cbxNombreCurso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxNombreCurso.setForeground(new java.awt.Color(0, 0, 0));
        cbxNombreCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione el curso-", "SQL Server Implementación", "SQL Server Administración", "Inteligencia de Negocios", "Programación Transact-SQL", "Java Fundamentos", "Java Cliente-Servidor", "Gestión de proyectos" }));
        cbxNombreCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNumVacantes.setEditable(false);
        txtNumVacantes.setBackground(new java.awt.Color(255, 255, 255));
        txtNumVacantes.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNumVacantes.setForeground(new java.awt.Color(0, 0, 0));
        txtNumVacantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Num. Vacantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtPrecioCurso.setEditable(false);
        txtPrecioCurso.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioCurso.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtPrecioCurso.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio del Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNomProfesor.setEditable(false);
        txtNomProfesor.setBackground(new java.awt.Color(255, 255, 255));
        txtNomProfesor.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNomProfesor.setForeground(new java.awt.Color(0, 0, 0));
        txtNomProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrecioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomProfesor)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtNumVacantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Alumno Datos");

        txtIdAlu.setBackground(new java.awt.Color(255, 255, 255));
        txtIdAlu.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtIdAlu.setForeground(new java.awt.Color(0, 0, 0));
        txtIdAlu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtEmailAlu.setEditable(false);
        txtEmailAlu.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailAlu.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtEmailAlu.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailAlu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNomAlumno.setEditable(false);
        txtNomAlumno.setBackground(new java.awt.Color(255, 255, 255));
        txtNomAlumno.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNomAlumno.setForeground(new java.awt.Color(0, 0, 0));
        txtNomAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtTelefonoAlu.setEditable(false);
        txtTelefonoAlu.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoAlu.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtTelefonoAlu.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoAlu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDireccionAlumno.setEditable(false);
        txtDireccionAlumno.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionAlumno.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtDireccionAlumno.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNomAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDireccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Empleado Datos");

        txtIdEmpleado.setEditable(false);
        txtIdEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtIdEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtIdEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtEmailEmpleado.setEditable(false);
        txtEmailEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtEmailEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNomEmpleado.setEditable(false);
        txtNomEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtNomEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNomEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtNomEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom. Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtApellidoEmpleado.setEditable(false);
        txtApellidoEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtApellidoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ape. Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtDireccionEmpleado.setEditable(false);
        txtDireccionEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionEmpleado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtDireccionEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel14)
                .addGap(0, 168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDireccionEmpleado)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoEmpleado)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Pago Datos");

        txtImporte.setEditable(false);
        txtImporte.setBackground(new java.awt.Color(255, 255, 255));
        txtImporte.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(0, 0, 0));
        txtImporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importe a pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtFechaPago.setEditable(false);
        txtFechaPago.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaPago.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtFechaPago.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        cbxNumCuotas.setBackground(new java.awt.Color(255, 255, 255));
        cbxNumCuotas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxNumCuotas.setForeground(new java.awt.Color(0, 0, 0));
        cbxNumCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxNumCuotas.setSelectedIndex(1);
        cbxNumCuotas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de cuotas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        cbxTipoMatri.setBackground(new java.awt.Color(255, 255, 255));
        cbxTipoMatri.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxTipoMatri.setForeground(new java.awt.Color(0, 0, 0));
        cbxTipoMatri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Elija la matricula-", "Normal", "Media beca" }));
        cbxTipoMatri.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        txtNota.setBackground(new java.awt.Color(255, 255, 255));
        txtNota.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtNota.setForeground(new java.awt.Color(0, 0, 0));
        txtNota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nota matrícula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoMatri, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel15)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoMatri, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("1. Ingresar los ID y luego presionar en Buscar. 2. Llenar los datos de pago, luego dar a Procesar. 3. Matricular");

        btnProcesarDatos.setBackground(new java.awt.Color(153, 255, 153));
        btnProcesarDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnProcesarDatos.setText("PROCESAR DATOS");
        btnProcesarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BtnBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnProcesarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnMatricularAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProcesarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMatricularAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnMatricularAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAlumnoActionPerformed
        try {
            //Datos 1
            Matricula matricula = new Matricula();
            matricula.setIdCurso(cbxNombreCurso.getSelectedIndex());
            matricula.setIdAlumno(Integer.parseInt(txtIdAlu.getText()));
            matricula.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            matricula.setTipoMatricula((String) cbxTipoMatri.getSelectedItem());
            matricula.setFecha(txtFechaPago.getText());
            matricula.setPrecio(Double.parseDouble(txtPrecioCurso.getText()));
            matricula.setNumCuotas((int) cbxNumCuotas.getSelectedItem());
            matricula.setNota(Integer.parseInt(txtNota.getText()));

            //Datos 2
            Pago pago = new Pago();
            pago.setIdCurso(cbxNombreCurso.getSelectedIndex());
            pago.setIdAlumno(Integer.parseInt(txtIdAlu.getText()));
            pago.setNumCuotas((int) cbxNumCuotas.getSelectedItem());
            pago.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            pago.setFechaPago(txtFechaPago.getText());
            pago.setImportePago(Double.parseDouble(txtImporte.getText()));

            // Proceso
            TechCenterController control = new TechCenterController();
            matricula = control.procesar(matricula);
            pago = control.procesar(pago);
            Mensaje.info(null, "Matricula creada exitosamente, el pago tambien ha sido guardado");

        } catch (Exception e) {
            Mensaje.error(null, e.getMessage());
        }
    }//GEN-LAST:event_btnMatricularAlumnoActionPerformed

    private void BtnBuscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarDatosActionPerformed
        try {
            TechCenterController control = new TechCenterController();

            //Seteando datos alumno
            txtEmailAlu.setText(control.buscarAlu(Integer.parseInt(txtIdAlu.getText())).getEmail());
            txtNomAlumno.setText(control.buscarAlu(Integer.parseInt(txtIdAlu.getText())).getNombre());
            txtTelefonoAlu.setText(control.buscarAlu(Integer.parseInt(txtIdAlu.getText())).getTelefono());
            txtDireccionAlumno.setText(control.buscarAlu(Integer.parseInt(txtIdAlu.getText())).getDireccion());

            //Seteando datos empleado
            txtIdEmpleado.setText(String.valueOf(control.obtIdEmpPorUsuario()));
            txtEmailEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getEmail());
            txtDireccionEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getDireccion());
            txtNomEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getNombre());
            txtApellidoEmpleado.setText(control.buscarEmp(Integer.parseInt(txtIdEmpleado.getText())).getApellido());

            //Seteando datos curso
            txtNumVacantes.setText(Integer.toString(control.buscarCurso(cbxNombreCurso.getSelectedIndex()).getNum_vacantes()));
            txtNomProfesor.setText(control.buscarCurso(cbxNombreCurso.getSelectedIndex()).getProfesor());
            txtPrecioCurso.setText(Double.toString(control.buscarCurso(cbxNombreCurso.getSelectedIndex()).getPrecio()));
        } catch (SQLException ex) {
            Logger.getLogger(RegMatriculasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBuscarDatosActionPerformed

    private void btnProcesarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarDatosActionPerformed
        try {
            TechCenterController control = new TechCenterController();
            String nombreCurso = (String) cbxNombreCurso.getSelectedItem();
            int numCuotas = Integer.parseInt(cbxNumCuotas.getSelectedItem().toString());
            String tipoMatricula = cbxTipoMatri.getSelectedItem().toString();

            double importe = control.calcularImporteCurso(nombreCurso, numCuotas, tipoMatricula);

            // Formatear el importe para mostrar solo dos decimales
            DecimalFormat decimalFormat = new DecimalFormat("#.00");
            String importeFormateado = decimalFormat.format(importe);

            txtImporte.setText(importeFormateado);

            String fechaPago = control.obtenerFechaActual();
            txtFechaPago.setText(fechaPago);
        } catch (SQLException ex) {
            Logger.getLogger(RegMatriculasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProcesarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarDatos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMatricularAlumno;
    private javax.swing.JButton btnProcesarDatos;
    private javax.swing.JComboBox<String> cbxNombreCurso;
    private javax.swing.JComboBox<String> cbxNumCuotas;
    private javax.swing.JComboBox<String> cbxTipoMatri;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtDireccionAlumno;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JTextField txtEmailAlu;
    private javax.swing.JTextField txtEmailEmpleado;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtIdAlu;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNomAlumno;
    private javax.swing.JTextField txtNomEmpleado;
    private javax.swing.JTextField txtNomProfesor;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtNumVacantes;
    private javax.swing.JTextField txtPrecioCurso;
    private javax.swing.JTextField txtTelefonoAlu;
    // End of variables declaration//GEN-END:variables
}
